openapi: "3.0.0"
info:
  version: 1.0.0
  title: Todo list Go Web app OAS
  description: OpenApi Specification for a sample API that uses a Todo list as an example
  contact:
    name: Todo API Team
    email: todo.team@goeland.io
    url: https://goeland.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://todo.goeland.io/api
components:
  schemas:
    NewTodo:
      type: object
      properties:
        task:
          type: string
          minLength: 5
      required:
        - task
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int32
        task:
          type: string
          minLength: 5
        completed:
          type: boolean
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
      required:
        - id
        - task
        - completed

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

paths:
  /todos:
    post:
      description: Creates a new todo
      operationId: createTodo
      requestBody:
        description: Todo to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: Todo creation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Returns all Todos
      description: Returns all the todo's of the user
      operationId: getTodos
      parameters:
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: get todo's response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        default:
          description: unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /todos/{todoId}:
    put:
      description: Updates the status of a todo
      operationId: updateTodo
      parameters:
        - name: todoId
          in: path
          description: Id of the todo
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: status of the todo
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                task:
                  type: string
                completed:
                  type: boolean
      responses:
        '200':
          description: put todo's succesfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: delete todo's when todoId was not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: delete a todo
      operationId: deleteTodo
      parameters:
        - name: todoId
          in: path
          description: Id of the todo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: delete todo's succesfull no content
        '404':
            description: delete todo's when todoId was not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



