// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package main

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewTodo defines model for NewTodo.
type NewTodo struct {
	Task string `json:"task"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed   bool       `json:"completed"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          int32      `json:"id"`
	Task        string     `json:"task"`
}

// GetTodosParams defines parameters for GetTodos.
type GetTodosParams struct {
	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// CreateTodoJSONBody defines parameters for CreateTodo.
type CreateTodoJSONBody NewTodo

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody CreateTodoJSONBody
